services:
  shiny-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3838:3838
    develop:
      watch:
        - action: rebuild
          path: .
networks:
  iatlas-network:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "192.168.7.7/24"
                gateway: "192.168.6.6"
